### ISSUE TITLE
Issue processing payments

### ISSUE THREAD

**Issue by bvpb** [spree/spree_gateway#105]
I've having some issues getting payments processed on a new store. I'm 
guessing it might be an issue with the spree gateway itself but i'm not 
sure. I'm expecting the test payment to be processed but instead the following happens.

Given a vanilla install with some basic extra steps (add a zone, shipping 
method, etc.) the payment fails with the following error:

"The card object must have a value for 'number'"

This happens on the confirmation step, the payment step succeeds without 
issue.

Looking in the log I see the following:

Gateway Error
--- !ruby/object:ActiveMerchant::Billing::Response
params:
error:
message: The card object must have a value for 'number'.
type: card_error
param: number
code: invalid_number
message: The card object must have a value for 'number'.
success: false
test: false
authorization: 
fraud_review: 
avs_result:
code: 
message: 
street_match: 
postal_match: 
cvv_result:
code: 
message:

I checked a bit further back in the log and the credit card details do 
appear to be submitted:
Started PATCH "/checkout/update/payment" for 127.0.0.1 at 2013-10-06 
16:27:28 +1100
Processing by Spree::CheckoutController#update as HTML
Parameters: {"utf8"=>"✓", 
"authenticity_token"=>"ULTMChoByuqOylMyc2kVfmDUPIWsHuZk+ytf6hvkgrY=", 
"order"=>{"payments_attributes"=>[{"payment_method_id"=>"6"}]}, 
"payment_source"=>{"6"=>{"number"=>"[FILTERED]", "expiry"=>"01 / 14", 
"verification_value"=>"[FILTERED]", "cc_type"=>"visa", 
"first_name"=>"Victor", "last_name"=>"Ramanauskas"}}, "state"=>"payment"}

Here is a comprehensive list of how to reproduce the issue:

Install spree(2.1 stable) as per current instructions
`gem install rails -v 4.0.0
gem install spree
rails _4.0.0_ new my_store
spree install my_store`

Create a new zone that includes Australia (for my testing purposes)
Create a shipping method for that zone, check "Default Shipping"
Add a payment method
- Stripe Gateway (Development, "Active" checked)
  Changed currency to AUD and added Stripe API key, server is listed as "test", "Test mode" checked
  Removed all other payment methods (I tried it with leaving these there and got an error, I remember reading once(!) that you can only have 1 type of method, so I removed them as I had no need for them otherwise)
  Add item to cart
  Checkout
  Enter address details
  Enter test credit card details
- 4242424242424242
- 01/14
- 123
  Reach confirmation screen, everything appears correct, Payment Information shows a Visa ending in 4242
  Click "Place Order"
  Receive message "The card object must have a value for 'number'"
  Payment Information is now blank.

`$ ruby -v
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin11.4.2]
$ rails -v
Rails 4.0.0`

Gemfile:

```
source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'spree', '2.1.1'
gem 'spree_gateway', :git => 'https://github.com/spree/spree_gateway.git', :branch => '2-1-stable'
gem 'spree_auth_devise', :git => 'https://github.com/spree/spree_auth_devise.git', :branch => '2-1-stable'
```

This gist contains the relevant log entries, starting at adding the payment method: https://gist.github.com/bvpb/6859403

**Comment by ams11** [comment]
I've just run into this issue again, using Spree 2.4.4.beta and activemerchant 1.44.1. After some digging around, it looks like Stripe may have changed their response schema - instead of using response.params['default_card'], it now appears to be using response.params["default_source"] to send the token back to us. So, my local change for now is just the following:

-          :gateway_payment_profile_id => response.params['default_card']
+         :gateway_payment_profile_id => response.params['default_card'] || response.params["default_source"]

Have you guys run across this? Does this need to go into Spree core, or are we doing something wrong in how we are communicating with Stripe in our app?

**Comment by JDutil** [comment]
It's been fixed by https://github.com/spree/spree_gateway/commit/9a8d03017cf28b2467550ca8f9c932f5090d878a make sure you're up to date on the 2-4-stable branch.

**Comment by ams11** [comment]
Perfect - thanks! I'll go ahead and upgrade the project to 2-4-stable.

**Comment by MattDunbar** [comment]
Can we reopen this? This patch should really be backported to older versions of Spree. I can confirm it is an issue in 2-3-stable.

**Comment by JDutil** [comment]
@MattDunbar update to latest 2-3-stable for https://github.com/spree/spree_gateway/commit/b87cd7f590b6fd034b9750ebc6cf4cf1cab3c591
