### ISSUE TITLE
getting "We are unable to calculate shipping rates for the selected items."

### ISSUE THREAD

**Issue by thiyagarajan** [spree/spree_gateway#135]
Hi

I am getting "We are unable to calculate shipping rates for the selected items." 

using spree 2.1.4 with gateway 2-1-stable branch
1. add product to cart
2. provide address with US location after login
3. getting message "We are unable to calculate shipping rates for the selected items." while submit

But its working without using spree_gateway with same configuration.

Please help us to resolve this issue!

**Comment by DeodorantMan** [comment]
When I added a country to the zone it started working. 
Also deleted the tmp/cache folder to make sure nothing was still interfering.

**Comment by samholst** [comment]
@JDutil Thank you! Totally overlooked that part!
