### ISSUE TITLE
Braintree::NotFoundError -- Stable-2.2

### ISSUE THREAD

**Issue by johnjameswhitman** [spree/spree_gateway#168]
I keep getting the following error in development.log when I try to submit a dummy/sandbox payment with Braintree:

```
Gateway Error
  --- Braintree::NotFoundError
...
```

The same error pops up on the view-side.

I've included the braintree gem in my Gemfile, snippet:

```
gem 'spree', '2.2.2'
gem 'spree_gateway', git: 'https://github.com/spree/spree_gateway.git', branch: '2-2-stable'
gem 'braintree', '~> 2.32'
```

Also have set up a sandbox account with braintree, added a new Spree::Gateway::BraintreeGateway payment method and configured it with my merchant account, public/private key, CSE key and an environment: of "sandbox". Am I missing any steps or potentially using the wrong version of the braintree gem?

For reference...
Gemfile: https://gist.github.com/johnjameswhitman/b9a3d9bec03a7a31d689
Gemfile.lock: https://gist.github.com/johnjameswhitman/1e8b49c8fb982c0fff7c

**Comment by sylvinho81** [comment]
@johnjameswhitman I am trying to use this gem, taking a look at my paypal developer account I can see next API credentials inside Sandbox test accounts.

username
password
signature

I guess the username is the information that I need to use in the field Merchant in the administration panel for Spree::Gateway::BraintreeVzeroPaypalExpress

**Comment by damianlegawiec** [comment]
@sylvinho81 please submit an issue in https://github.com/spree-contrib/spree_braintree_vzero - this isn't related to `spree_gateway` - thanks!
