### ISSUE TITLE
Spree::Gateway::StripeGateway retrieve customer id

### ISSUE THREAD

**Issue by james075** [spree/spree_gateway#183]
So far, I follow theses steps:

1- create order
2- add lines to order
3- fill user's delivery + shipping address
4- checkout with `payment_attributes` and `payment_source`:

``` swift
        let params = ["order": [
            "payments_attributes": [
                [ "payment_method_id": 1]
            ]
        ],
        "payment_source": [
            1: [
                "number": "4242424242424242",
                "month": "1",
                "year": "2020",
                "verification_value": "123",
                "name": "Test Test"
            ]]]
```

I would retrieve stripe's `custumer_id` then perform a request to stripe to get all its **cards** and fill the **payment_source** with a **chosen card**.

Hi, I have some questions:
- When do you create stripe customer ? I looked at and it seems to be created at the same time as the user performs a complete checkout ?
- Why stripe customer id is not unique to `Spree::User` ?
  For each completed checkout, it looks like you create a new customer into Stripe for the payment
- Can I retrieve stripe's `customer id` via `spree user` from spree API ?
- What is the right way to checkout a cart from the api ?

Thanks a lot.

**Comment by vmatekole** [comment]
@JDutil out of the box new customers continue to be created on each order with 3-0-stable branch. Should I expect this? If so can you point me to relevant docs where I can determine how to reuse payment profile information, avoiding the duplication of data at Stripe.

**Comment by JDutil** [comment]
@vmatekole https://stripe.com/docs/api#create_charge the issue may be that we only pass the source token and not the customer token as well.

**Comment by vmatekole** [comment]
@JDutil is there anyway of overriding this behaviour? Beyond rolling my own custom payment method?

**Comment by JDutil** [comment]
You can try updating the spree implementation to also pass the customer token as well as the payment token otherwise no.

**Comment by shivabhusal** [comment]
This might help
https://cbabhusal.wordpress.com/2016/03/17/rails-spree-get-the-gateway-and-other-payment-information/
