### ISSUE TITLE
Spree::Gateway::AuthorizeNet -- incorrect code passing :test flag to ActiveMerchant code for test mode [ALL VERSOINS]

### ISSUE THREAD

**Issue by jasonfb** [spree/spree_gateway#193]
please note this is a separate bug from the other bug I just filed. 

There is a coding confusion between the concept of “test mode” and using the “test server” in written into the code itself.  
```
def options_with_test_preference
  options_without_test_preference.merge(:test => self.preferred_test_mode)
end
```
(see https://github.com/spree/spree_gateway/blob/2-3-stable/app/models/spree/gateway/authorize_net.rb#L11)

This basically passes a flag for test to the options swept up by ActiveMerchant::Billing::AuthorizeNetGateway. However, the “test” flag expected by ActiveMerchant::Billing::AuthorizeNetGateway makes that object work with the TEST SERVER. It has no effect on test mode, which is an entirely different thing (but as you can see, it is tied to a Spree preference for test mode— this is just incorrect as far as I can tell). You can clearly documented this way here if you read the comments in the initialize method on object ActiveMerchant::Billing::AuthorizeNetGateway https://github.com/Shopify/active_merchant/blob/v1.43.1/lib/active_merchant/billing/gateways/authorize_net.rb 

The bug is in all version of this gem back to 2-0-stable.

**Comment by JDutil** [comment]
Fixed by https://github.com/spree/spree_gateway/commit/f4d6cce5b40473e018657dad413aaa238844ccad
