### ISSUE TITLE
Feature: Adding support for simplify payment gateway

### ISSUE THREAD

**Issue by leckylao** [spree/spree_gateway#207]
Hi,

I've started a branch to work on supports for https://www.simplify.com/commerce payment gateway. Now just had the purchase working. It's still in WIP. Creating the issue in order to reduce duplicate work and putting things together :smile:

**Comment by JDutil** [comment]
If you have a WIP (work in progress) branch feel free to submit a PR for people review/contribute to.  I'm going to close this out for housekeeping as a feature request.
