### ISSUE TITLE
linkpoint no longer used by FirstData

### ISSUE THREAD

**Issue by westlakem** [spree/spree_gateway#213]
I'm not exactly sure how spree_gateway uses activeMerchant yet (I'm just starting to get into spree) but LinkPoint is no longer available through FirstData.  I've already added an issue to active_merchant, but I thought I would list it here as well, as I'm not sure where the change needs to be made (maybe both places)

LinkPoint is no longer used by FirstData (can be seen by going to http://www.firstdata.com/linkpoint/) They instead are using payeezy for ecommerce solutions (https://www.firstdata.com/en_us/products/merchants/ecommerce/payeezy-ecommerce-solution.html) In order to continue use FirstData solutions, we need payeezy integrated and there's already a gem for it (https://github.com/payeezy/payeezy_ruby).

**Comment by JDutil** [comment]
spree_gateway is just a wrapper around active_merchant.  If LinkPoint is longer valid we should just remove the wrapper https://github.com/spree/spree_gateway/blob/master/app/models/spree/gateway/linkpoint.rb

The best way to implement payeezy would be to write an extension specifically for it using the payeezy_ruby library.  If active merchant implements payeezy than we could add it here with their implementation.

**Comment by westlakem** [comment]
Ok, I'll keep on the lookout for active_merchant to integrate it first and then update what they say about it. 

     On Friday, March 6, 2015 4:06 PM, Jeff Dutil <notifications@github.com> wrote:
   

 spree_gateway is just a wrapper around active_merchant. If LinkPoint is longer valid we should just remove the wrapper https://github.com/spree/spree_gateway/blob/master/app/models/spree/gateway/linkpoint.rbThe best way to implement payeezy would be to write an extension specifically for it using the payeezy_ruby library. If active merchant implements payeezy than we could add it here with their implementation.—
