### ISSUE TITLE
Authorize.net CIM - "The original transaction was not issued for this payment profile" when trying to issue a refund

### ISSUE THREAD

**Issue by jasonfb** [spree/spree_gateway#215]
We're getting  "E00051  - The original transaction was not issued for this payment profile" when trying to issue a refund on some (not all) of refund transactions.

The docs say "If the customer profile ID, payment profile ID, and shipping address ID are included, they must match the original transaction"

Digging into it a little, I have determined that what is happening here is that the shipping address being sent for the refund transaction is not the same as the shipping address that was originally sent for the transaction. 

Has anyone seen this before?

**Comment by jasonfb** [comment]
We're on Spree & Spree gateway 2.1

**Comment by jasonfb** [comment]
I think this is related to https://github.com/spree/spree_gateway/issues/174 ? 

Seems like the same root cause.

**Comment by jasonfb** [comment]
I'm still digging into this, trying to parse out what is going on. Although I do not have a specific root cause right now, please keep issue open until I have it fully investigated. 

I noticed a change between 2.1 and 2.2

notice line 117 -- see how it is commented out in Spree 2.1

https://github.com/onedanshow/spree_gateway/blob/2-1-stable/app/models/spree/gateway/authorize_net_cim.rb#L117

but not in spree 2.2...

https://github.com/onedanshow/spree_gateway/blob/2-2-stable/app/models/spree/gateway/authorize_net_cim.rb

Does this line mean that when a CIM profile is created it is always created in Spree 2.1 it is always created without a billing address?

**Comment by JDutil** [comment]
Appears it is always created without a shipping address in 2.1.

**Comment by jasonfb** [comment]
Interesting. Seems related (in fact if not the same as?) #174 ?

I haven't debugged it deeply (in fact, it's pretty hard to since to recreate it I need to hit the actual Production gateway), maybe the original create profile creates a CIM credit card without a shipping address, and when the refund transaction goes through it then uses an address? This would cause the symptom.

We are upgrading to Spree 2.2 on Saturday morning, so I will keep an eye on this to see if the root cause is addressed there.

**Comment by JDutil** [comment]
Yea it does sound like the refund gets the address sent, but since it's not properly sent during the payment due to 174 it causes the mismatch.  Let us know if upgrading to 2.2. helps.

**Comment by jasonfb** [comment]
We are still working on this, and we are still seeing these in Spree 2.2. However, my current working hypothesis is that this is caused by our code, not Spree code.

**Comment by tamagokun** [comment]
I've had this problem occur only once in production when trying to do a refund, and it seems to be a confirmed bug after ticket placed with auth.net. Here's the response:

---

"Reviewing the code provide we see the merchants system is using an older method of submitting refunds using profile ids. There is a bug that has been identified with the two calls they are using createCustomerProfileTransactionRequest and profileTransRefund. This is also an older way of submitting refund/credit transactions.

The issue will appear only if these conditions are met:

The original transaction is an auth only
The prior auth capture transaction follow-on request is sent with NO profile ids
The refund is sent with profile ids.
It is recommended to use createTransactionRequest and provide the transaction id like in the example provided here: http://developer.authorize.net/api/reference/index.html#payment-transactions-refund-a-transaction"

---

Does ActiveMerchant even use any of their newer APIs?

**Comment by jasonfb** [comment]
basically, the old spree code is dead. As you can see from their response above, the Spree code is written to use old Authorize Net implementation.

We had this problem plague us for several YEARS. In fact, I worked professionally with Authorize Net for nearly 11 years (yes, I did my first Authorize Net integration in 2005 in PHP!). As of last month, I am pleased to reported that I switched my company over to Braintree and we are about 1000 times happier.

Not only is Braintree just a full-out better platform, it is much less buggy. Working with Authorize Net over an 11 year period led me to believe that their platform is just inherently buggy and badly designed. (Hey, they came from a time when it was cool to have a ".net" domain name-- does anyone remember that or am I the old fuddy-duddy?)

So... my professional advice is: If someone says Authorize Net to you, don't walk, run. Get as far away from the horrible platform as fast as you possibly can.  These people have created and profited from so much vendor lock-in it is astonishing. It is only a matter of time before they go bankrupt-- they are really that bad.

**Comment by jasonfb** [comment]
>>Does ActiveMerchant even use any of their newer APIs?

No big Spree stores that I know of still uses Authorize NET AFAIK-- I know for a FACT that no store on Solidus has ever used Authorize Net (as of last May 2016 -- I can tell you how I know this to be true), and basically the community-wide consensus is that Auth Net is a crappy platform and should be migrated away from as soon as possible. 

You are looking at graveyard code. Run away. Danger. If you value your sanity do the smart thing and switch payment processors.

**Comment by jasonfb** [comment]
Oh and this WAS indeed one of the reasons -- along with other bugs that Authorize Net never fixed --- that we moved away from them.

**Comment by tamagokun** [comment]
Oh no doubt, it's really frustrating having to deal with auth.net after using Braintree or Stripe for so many other projects. Client wanted to use auth.net since they were using it before, but I don't think they'll want to pay for me to update old code. We already use Braintree for Paypal express payments, so I think its time to recommend using Braintree for CC as well.

Thanks for the feedback. The fact that auth.net says there is a bug but then recommends ME to update code on my end is nuts. They should fix their product, right?

**Comment by jasonfb** [comment]
>>They should fix their product, right?

I agree. But consider that a lot of Spree got written in 2010 and 2011 and a lot of stuff is just cruft. It *is* normal for APIs to change (like theirs), but in this case, no one in the Spree community has really cared that much to go change Spree to work against their new system. Probably, it's because they ____ [insert pejorative of your choice which I shall not leave in public Github comments]

So, the face that Spree never advanced past 2012 in this area is sort of like a self-fulfilling prophecy. Since they ____ so much, people left them, and since people left them, no one in Spree cared to re-write it.

**Comment by tamagokun** [comment]
Makes sense! Thanks again
