### ISSUE TITLE
Crash in Spree::CheckoutController#confirm_skrill

### ISSUE THREAD

**Issue by jasonfb** [spree/spree_gateway#220]
IN Spree 2.3, I'm getting a crash on this line of code:

https://github.com/spree/spree_gateway/blob/2-3-stable/lib/controllers/frontend/spree/checkout_controller_decorator.rb#L41

fullstack trace:
https://gist.github.com/anonymous/dbb8a5c710818a6f5e8f

I'm not actually running a store with a Skrill payment method. Is there an easy/effective way to kill the before_filter in this decorator?

I tried overriding the confirm_skill method and also a skip_before_fitler :confirm_skrill but neither worked -- which makes me think the gem decorator is loaded after my decorator but I'm not 100% sure about that

I wonder why the gateway-specific code is in the common methods? I guess it seems like the before_filter should only be set if the store uses Skrill, as my store is now running through these lines of code even though it doesn't use Skrill

**Comment by jasonfb** [comment]
a simple defensive patch would look like this:

https://github.com/mackweldon/spree_gateway/commit/bef3be800af0943d2bc2bf9f704c27aeeb1af1bb

**Comment by JDutil** [comment]
Yea I would prefer gateway specific stuff like this skrill confirm were done in their own extensions.  This should be purely ActiveMerchant gateways IMO, but someone back in the day stuck skrill in here... Not sure who uses it but will apply your patch for now.
