### ISSUE TITLE
Skrill should be removed into it's own extension.

### ISSUE THREAD

**Issue by JDutil** [spree/spree_gateway#221]
See #220 there is no reason non ActiveMerchant gateways should be in here.  They should be their own extensions.

**Comment by alepore** [comment]
@JDutil related: i'll probably need to build a Braintree v.zero integration, using the normal activemerchant braintree gateway but probably also some custom javascripts and templates.
It's better to create a separate extension or to try to integrate here (in a clean way, of course)

**Comment by alexw23** [comment]
Agreed +1

**Comment by alexw23** [comment]
It even creates its own table - how many people are actually using skrill?

**Comment by JDutil** [comment]
Unfortunately there is no way of knowing that besides removing it, and waiting for someone to notice.

**Comment by narichvirus1** [comment]
Sory
