### ISSUE TITLE
PAYMENT STATE not changing

### ISSUE THREAD

**Issue by GraphicDesk** [spree/spree_gateway#222]
Hello,

I'm using Braintree on a basic Spree 3.0.0 instalation.

I created an sandbox account and added the merchant id and key's in the Admin panel for Braintree.
I am able to complete an order all seems ok but in the Order section the payment state  will have the status balance due.
This is common behavior? Should not be changing to "paid" ?
![selection_001](https://cloud.githubusercontent.com/assets/8121277/7220524/253ef3e4-e6d3-11e4-89d3-6455c52083e2.png)

Isn't Braintree confirming the transfer of funds even if it's a sandbox env. ?

**Comment by JDutil** [comment]
That depends on whether or not you have auto-capture turned on or not.  If you don't you are only authorizing the card at checkout, and still need to capture the payment before it will be marked as paid. If you want to capture on checkout set `Spree::Config.auto_capture = true` if you want to capture at time shipment is made, which is best practice for companies like Amazon you can set `Spree::Config.auto_capture_on_dispatch = true` close:question

**Comment by JDutil** [comment]
close:question

**Comment by JDutil** [comment]
No spreebot on this repo :(
