### ISSUE TITLE
Spree payment method doesn't implement cancel?

### ISSUE THREAD

**Issue by nathanaeljones** [spree/spree_gateway#223]
NotImplementedError: You must implement cancel method for this payment method.

```
e-9265912534c8/core/app/models/spree/payment_method.rb:  72:in `cancel'
…65912534c8/core/app/models/spree/payment/processing.rb:  67:in `cancel!'
…gems/spree-9265912534c8/core/app/models/spree/order.rb: 692:in `block in after_cancel'
…gems/spree-9265912534c8/core/app/models/spree/order.rb: 692:in `after_cancel'
````

**Comment by JDutil** [comment]
Whatever payment method your using that inherits from Spree::PaymentMethod should implement a cancel action.

**Comment by nathanaeljones** [comment]
Thanks, turned out I was using a older version of spree_gateway, updating fixed it. Should have checked first.
