### ISSUE TITLE
Question: Is there any universal redirect payment method?

### ISSUE THREAD

**Issue by plod-shooter** [spree/spree_gateway#227]
I'd like to use payment system that is not coded to RoR yet, so there is no ActiveMerchant or Spree plugin for that system.
I'd like to use most simple form of payment - via redirect. But should I really write a lot of code to make it possible? Is there any payment method of redirect payment to merchant's payment gateway? I mean I dont' want to pass credit card and address details. All I want is to redirect user to merchant's payment page so there user will leave all that details and after payment's completed (or not) the user be redirected to my spree shop?
Thanks!

**Comment by JDutil** [comment]
You could look at how https://github.com/spree-contrib/better_spree_paypal_express or https://github.com/spree-contrib/spree-adyen or other billing integrations work.  This extension is purely meant for activemerchant gateways.
