### ISSUE TITLE
Braintree create_profile method unable to store default credit cards

### ISSUE THREAD

**Issue by philbattos** [spree/spree_gateway#228]
I think the Braintree [```create_profile```](https://github.com/spree/spree_gateway/blob/master/app/models/spree/gateway/braintree_gateway.rb#L55) method contains a small bug. 

```ruby
    def create_profile(payment)
      if payment.source.gateway_customer_profile_id.nil?
        response = provider.store(payment.source, options_for_payment(payment))

        if response.success?
          payment.source.update_attributes!(:gateway_customer_profile_id => response.params['customer_vault_id'])
          cc = response.params['braintree_customer'].fetch('credit_cards',[]).first
          update_card_number(payment.source, cc) if cc
        else
          payment.send(:gateway_error, response.message)
        end
      end
    end
```

When Spree [assigns a default credit card](https://github.com/spree/spree/blob/master/core/app/models/spree/order/checkout.rb#L296) to an order, it [creates a new payment](https://github.com/spree/spree/blob/master/core/app/models/spree/order/checkout.rb#L299), which triggers the [```create_payment_profile```](https://github.com/spree/spree/blob/master/core/app/models/spree/payment.rb#L190) method, which then calls the [```create_profile```](https://github.com/spree/spree/blob/master/core/app/models/spree/payment.rb#L198) method above. However, when ```#create_profile``` is called in this way, the payment source (a credit card) does not contain the associated credit card number and cvv because those details are not stored. So when ```provider.store()``` is called, Braintree rejects the card because it cannot be verified. The problem is that this payment rejection happens before the customer has had a chance to enter payment details (since ```#assign_default_credit_card``` is called before the order transitions to the payment state). 

So i think there needs to be an additional check on the first line of ```#create_profile``` to ensure that the card is only sent to Braintree when the credit card number is present. If it is not present, the gateway should not attempt to store the card with Braintree. In my project, i've replaced this line
```ruby
if payment.source.gateway_customer_profile_id.nil?
```
with this:
```ruby
if payment.source.gateway_customer_profile_id.nil? && payment.source.number.present?
```

This problem could also be remedied by ensuring that all default credit cards contain a ```gateway_customer_profile_id``` but we have many customers with cards that do not contain a value for that field and it is not possible to update them all with the correct profile_id.

**Comment by JDutil** [comment]
I think your fix is good if you want to submit a PR

**Comment by robertwclark** [comment]
Please confirm this fix is moving to stable code. I cannot process production braintree transactions, but development environment sandbox works. I am missing something for the production environment?
