### ISSUE TITLE
Braintree multi currency solution

### ISSUE THREAD

**Issue by tomaswitek** [spree/spree_gateway#236]
There is no Braintree solution if you want to sell your products in multiple currencies.
Braintree itself allows it by creating a multiple Merchant Account IDs for each currency.
https://articles.braintreepayments.com/get-started/currencies#multi-currency-setups

I've created a simple workaround for it: 
https://github.com/spree/spree_gateway/pull/235/files

**Comment by JDutil** [comment]
closing in favor of your pr
