### ISSUE TITLE
Remove sensitive files from repo history

### ISSUE THREAD

**Issue by platramos** [spree/spree_gateway#237]
The .env.development needs to be removed. Since we are using dotenv (http://www.gotealeaf.com/blog/managing-environment-configuration-variables-in-rails) as our environment variable control tool we should store this types of files locally only and add it to the gitignore. If anything keep a .env.example file so it will be easy to know what kinds of things should go in there.

**Comment by JDutil** [comment]
@platramos those files don't exist... or do you mean there is a git history of it previously existing?

**Comment by platramos** [comment]
I think I submitted this issue for the wrong github repo. Sorry for the
inconvenience and you can delete this!
