### ISSUE TITLE
We are unable to calculate shipping rates for the selected items.

### ISSUE THREAD

**Issue by bilalashraf980** [spree/spree_gateway#263]
Hello everyone please guide me 
 add the products in cart and add zone and also added shipping method can't understand why this error is occur so please guide

**Comment by damianlegawiec** [comment]
@bilalashraf980 it's not an gateway issue, check if you have shipping methods for shipping zone (countries) for address submitted in the checkout

**Comment by bilalashraf980** [comment]
hi damianlegawiec 
yes i have shipping method for shipping zone then i do n't know why this error occur

**Comment by bilalashraf980** [comment]
![screenshot from 2016-11-14 18 06 42](https://cloud.githubusercontent.com/assets/10117549/20265870/30b6530c-aa95-11e6-93ed-09f41b884377.png)

**Comment by bilalashraf980** [comment]
please check . this is my shipping method
