### ISSUE TITLE
ArgumentError (Missing required parameter: login)

### ISSUE THREAD

**Issue by krishnarohitreddy** [spree/spree_gateway#267]
Gemfile includes

gem 'spree', '~> 3.2.0.rc1'
gem 'spree_auth_devise', '~> 3.2.0.beta'
gem 'spree_gateway', '~> 3.2.0.beta'

Gateway used stripe, configured via admin panel

Spree::Gateway::StripeGateway

SECRET KEY:  set,
PUBLISHABLE KEY: set;

test_mode: yes

**Comment by symarys** [comment]
Hello @krishnarohitreddy, can you check if upgrading spree to `3.2.0.rc3` fixes your issue?

**Comment by krishnarohitreddy** [comment]
@symarys It is working now, thank you.
