### ISSUE TITLE
red test suite prior to adding changes

### ISSUE THREAD

**Issue by joshRpowell** [spree/spree_gateway#274]
@damianlegawiec when I fork and run the full suite I expect it to be green before making any changes. 

but I get a failure here `./spec/features/stripe_checkout_spec.rb:79 # Stripe checkout shows an error with invalid security fields`

This was the commit that attempted to repair an issue in the past: [`7ea7f4fb`](https://github.com/spree/spree_gateway/pull/261/commits/7ea7f4fb8339aa0430787b0e991ef08f8b575094)

any thoughts?

**Comment by damianlegawiec** [comment]
Fixed :)
