### ISSUE TITLE
This transaction cannot be processed. Please enter a valid credit card number and type.

### ISSUE THREAD

**Issue by justinemar** [spree/spree_gateway#293]
I'm Using the built in Paypal Gateway payment method on spree 3.3.0 , i configured the setting from the admin backend, I have two sandbox accounts a seller and a buyer account. Here's my configuration for the backend (admin)

```
PROVIDER: Spree::Gateway::PayPalGateway
LOGIN:seller-sandbox_api1.gmail.com
PASSWORD: sellerpass
SIGNATURE: sellersignature
CURRENCY CODE: USD
SERVER: test
test checkbox: checked
display: both
autocapture: false(app default)
```
On the checkout i used the buyer sandbox credit card info that have a balance of 9999.00 USD and it still gives the error

> This transaction cannot be processed. Please enter a valid credit card number and type.

**Comment by Cabbit** [comment]
I am having this issue myself, it seems to have just started after the upgrade to spree 3.3 after working on spree 2.2 for quite some time. I only picked it up when I noticed a lot more people using the express checkout than the credit card checkout.

```
PROVIDER: Spree::Gateway::PayPalGateway
SERVER: live
test checkbox: un-checked
```

**Comment by Cabbit** [comment]
It looks like <n2:CreditCardNumber/> is empty, I'll see if I can backtrace where this should be set.

**Comment by Cabbit** [comment]
Remove your spree_braintree_vzero and it should work @justinemar it seems to be something in that gem that removes the credit card number.

**Comment by justinemar** [comment]
This issue is fixed, thanks @Cabbit
