### ISSUE TITLE
The VendorName is invalid or the account is not active

### ISSUE THREAD

**Issue by chrise86** [spree/spree_gateway#7]
I keep getting the following when trying to use SagePay:

<code>! '4000 : The VendorName is invalid or the account is not active.'</code>

I'm not sure whether there's a problem with the code or the details I'm using, could someone please confirm exactly what details need to go in the fields in the payment method backend, i.e. what goes in login/account and where these details come from.

The login I'm using currently is a developer account.

Spree 1.0.0 and Rails 3.1.3

**Comment by kuldeep3020** [comment]
i have facing the issue when i click on payment button in magento 
'4000 : The VendorName is invalid or the account is not active.'
can anyone help me to this figure out.thanks in advance
